# Generated by Django 3.1 on 2020-08-20 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Identity',
            fields=[
                ('employee_id', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('social_id', models.CharField(blank=True, max_length=24, null=True, unique=True)),
                ('health_id', models.CharField(blank=True, max_length=24, null=True, unique=True)),
                ('housing_id', models.CharField(blank=True, max_length=24, null=True, unique=True)),
                ('tax_id', models.CharField(blank=True, max_length=24, null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Identities',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='human.identity')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=32, null=True)),
                ('address00', models.CharField(max_length=128, verbose_name='Apt# and Street')),
                ('address01', models.CharField(max_length=128, verbose_name='Purok, Sitio, or Village')),
                ('address02', models.CharField(max_length=128, verbose_name='Barangay')),
                ('address03', models.CharField(max_length=128, verbose_name='Locality')),
                ('address04', models.CharField(max_length=128, verbose_name='Province')),
                ('address05', models.CharField(choices=[('Ilocos Region', 'REG-I'), ('Cagayan Valley Region', 'REG-II'), ('Cordillera Administrative Region', 'CAR'), ('Central Luzon Region', 'REG-I'), ('National Capital Region', 'NCR'), ('Calabarzon Region', 'REG-IVA'), ('Mimaropa Region', 'REG-IVB'), ('Bicol Region', 'REG-V'), ('Western Visayas Region', 'REG-VI'), ('Central Visayas Region', 'REG-VII'), ('Eastern Visayas Region', 'REG-VIII'), ('Zamboanga Peninsula Region', 'REG-IX'), ('Norther Mindanao Region', 'REG-X'), ('Davao Region', 'REG-XI'), ('Soccsksargen', 'REG-XII'), ('Caraga Region', 'REG-XIII'), ('Bangsamoro Autonomous Region in Muslim Mindanao', 'BARMM')], max_length=128, verbose_name='Region')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='human.identity')),
                ('last_name', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(max_length=64)),
                ('gender', models.CharField(choices=[('Male', 'M'), ('Female', 'F')], default='', max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='human.identity')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='enterprise/src/assets/human/photos/')),
                ('position', models.CharField(blank=True, max_length=64, null=True)),
                ('department', models.CharField(blank=True, max_length=64, null=True)),
                ('started', models.DateField(blank=True, null=True)),
                ('ended', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
