# Generated by Django 3.1 on 2020-08-28 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('human', '0003_employee_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily',
            fields=[
                ('time_in', models.DateTimeField(auto_created=True)),
                ('employee_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='human.identity')),
                ('time_out', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
