# Generated by Django 3.1 on 2020-08-28 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='time_in',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='daily',
            name='time_out',
            field=models.DateTimeField(),
        ),
    ]
