# Generated by Django 3.1 on 2020-08-28 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_auto_20200828_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daily',
            name='time_out',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
